metrics_per_epoch 2
edeno/franklab_mountainsort pull request #17
Opened 2020-06-23 05:09 UTC by shijiegu

Now everything is working. Please be careful now to change the code too much again.

2020-06-24 22:04 UTC, edeno approved these changes

2020-06-24 22:04 UTC, edeno commented on franklab_mountainsort/core.py
> +METRICS_OUTPUT = 'metrics_merged_tagged.json'
Delete

2020-06-24 22:04 UTC, edeno commented on franklab_mountainsort/ms4_franklab_proc2py.py
> -def tagged_curation(cluster_metrics, metrics_tagged,
Add this back

2020-06-24 22:04 UTC, edeno commented on franklab_mountainsort/ms4_franklab_proc2py.py
> -def get_mda_list(animal, date, ntrode, data_location):
Add this back

2020-06-24 22:04 UTC, edeno commented on franklab_mountainsort/ms4_franklab_pyplines.py
> -def add_curation_tags(dataset_dir, output_dir, firing_rate_thresh=0.01,
Change this back.

2020-06-24 22:04 UTC, edeno commented on franklab_mountainsort/ms4_franklab_pyplines.py
> -        metrics=os.path.join(dataset_dir, metrics_input),
Change this back.

2020-06-24 22:04 UTC, edeno commented on franklab_mountainsort/ms4_franklab_pyplines.py
> -        metrics_tagged=os.path.join(output_dir, metrics_output),
Change this back.

2020-06-29 17:59 UTC, edeno requested changes

2020-06-29 17:59 UTC, edeno commented on franklab_mountainsort/ms4_franklab_proc2py.py
> +def get_mda_list(anim, date, ntrode, data_location):
`anim` should be `animal`

2020-06-29 17:59 UTC, edeno commented on franklab_mountainsort/core.py
> +METRICS_OUTPUT = 'metrics_merged_tagged.json'
Still need to delete.

2020-06-29 20:42 UTC, shijiegu commented
Hey Eric! I just updated!

2020-06-29 20:44 UTC, edeno approved these changes

2020-06-29 20:44 UTC, merged